spring:
  application:
    name: seathappens

  datasource:
    url: jdbc:postgresql://localhost:5432/seathappens
    username: postgres
    password: postgres

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true

server:
  port: 8080

springdoc:
  swagger-ui:
    path: /swagger-ui.html

seathappens:
  reservation:
    duration-minutes: 10