input {
  tcp {
    port => 5001
    codec => json_lines
  }
}

filter {
  mutate {
    add_field => {
      "service" => "seathappens"
      "environment" => "local"
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "seathappens-logs-%{+YYYY.MM.dd}"
  }

  stdout {
    codec => rubydebug
  }
}
